# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

# Code coverage for R: see example at https://github.com/codecov/example-r

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
